# version de docker
version: '3.8'

services: 
  nestapp:
    build: cesarausa/eccomerce-dev-ausa
    container_name: ecommerce-docker
    ports:
      - "3000:3000"
    env_file:
      - .development.env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    container_name: ecommerce-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .development.env
 
volumes:
  pgdata: